export PYTHONPATH=$PYTHONPATH:/fs-computility-new/upzd_share/maoxinjie/AIVC/mxj/perturbench-main/src
export TMPDIR=/tmp  # 避免 AF_UNIX path too long
HYDRA_FULL_ERROR=1 train \
    data=mix_pert \
    data.embedding_key='scgpt_embeddings' \
    data.data_path='./data/norman_hvg_emb.h5ad' \
    model=cpa \
    model.use_cell_emb=true \
    logger=wandb \
    trainer.log_every_n_steps=10 \
    trainer.max_epochs=1 \
    trainer.min_epochs=0 \
    trainer.devices=[0] \
    model.use_mask=false \