export PYTHONPATH=$PYTHONPATH:/fs-computility-new/upzd_share/maoxinjie/AIVC/mxj/perturbench-main/src
export TMPDIR=/tmp  # 避免 AF_UNIX path too long
HYDRA_FULL_ERROR=1 train \
 trainer.devices=[0] \
 data=mix_pert \
 data.embedding_key='scgpt_embeddings' \
 logger=wandb \
 model=prnet \
 data.data_path='./data/sciplex3_highdose_emb.h5ad' \
 model.use_cell_emb=true \
 model.use_mask=false \
 trainer.min_epochs=0 \
 trainer.max_epochs=1 \
 trainer.log_every_n_steps=5
# callbacks.early_stopping.patience=5